In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [12]:
#Reading necessary data files
sono= pd.read_csv("Sonoma_weather_month.csv")
coast= pd.read_csv("CCoast_weather_month.csv")
valley= pd.read_csv("CValley_weather_month.csv")

In [86]:
sono2 = sono.groupby("date").mean() #some months have multiple stations recording data, decided to average all stations
coast2 = coast.groupby("date").mean()
valley2  = valley.groupby("date").mean()

In [15]:
sono2

,CDSD,CLDD,DP01,DP10,DP1X,DSND,DSNW,DT00,DT32,DX32,...,EMSN,EMXP,EMXT,HDSD,HTDD,PRCP,SNOW,TAVG,TMAX,TMIN
date,,,,,,,,,,,,,,,,,,,,,
1994-01-01T00:00:00,0.0,0.0,10.000000,4.000000,1.000000,0.0,0.0,0.0,8.0,0.0,...,0.0,1.160000,67.0,NaN,449.0,3.360000,0.0,47.6,59.5,35.8
1994-02-01T00:00:00,0.0,0.0,11.000000,9.000000,1.000000,0.0,0.0,0.0,7.0,0.0,...,0.0,1.000000,73.0,NaN,385.0,5.460000,0.0,49.1,60.9,37.3
1994-03-01T00:00:00,2.0,2.0,2.000000,1.000000,0.000000,0.0,0.0,0.0,1.0,0.0,...,0.0,0.210000,82.0,NaN,244.0,0.230000,0.0,56.2,71.0,41.3
1994-04-01T00:00:00,NaN,NaN,6.000000,4.000000,0.000000,0.0,0.0,0.0,0.0,NaN,...,0.0,0.590000,NaN,NaN,NaN,1.330000,0.0,NaN,NaN,42.7
1994-05-01T00:00:00,NaN,14.0,5.000000,3.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.600000,90.0,NaN,96.0,1.370000,0.0,62.0,76.6,47.4
1994-06-01T00:00:00,NaN,92.0,1.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.050000,105.0,NaN,11.0,0.050000,0.0,68.0,87.5,48.5
1994-07-01T00:00:00,NaN,90.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,96.0,4.0,4.0,0.000000,0.0,67.9,84.6,51.1
1994-08-01T00:00:00,NaN,134.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,102.0,5.0,0.0,0.000000,0.0,70.2,90.1,50.2
1994-09-01T00:00:00,NaN,85.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,98.0,12.0,7.0,0.000000,0.0,67.9,86.0,49.9
1994-10-01T00:00:00,NaN,12.0,2.000000,2.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.440000,88.0,114.0,102.0,0.590000,0.0,61.8,78.9,44.8
1994-11-01T00:00:00,NaN,0.0,9.000000,5.000000,2.000000,0.0,0.0,0.0,7.0,0.0,...,0.0,2.000000,78.0,564.0,450.0,6.490000,0.0,48.4,59.6,37.2
1994-12-01T00:00:00,NaN,0.0,12.000000,9.000000,0.000000,0.0,0.0,0.0,7.0,0.0,...,0.0,0.900000,64.0,1071.0,508.0,3.910000,0.0,45.6,54.8,36.3
1995-01-01T00:00:00,0.0,0.0,20.000000,18.000000,7.000000,0.0,0.0,0.0,2.0,0.0,...,0.0,4.280000,70.0,1475.0,403.0,20.290000,0.0,51.2,57.5,44.8
1995-02-01T00:00:00,0.0,0.0,2.000000,2.000000,0.000000,0.0,0.0,0.0,2.0,0.0,...,0.0,0.640000,78.0,1762.0,287.0,0.820000,0.0,54.0,63.6,44.4
1995-03-01T00:00:00,0.0,0.0,16.000000,14.000000,4.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,2.900000,74.0,2115.0,353.0,13.300000,0.0,52.8,63.0,42.5
1995-04-01T00:00:00,0.0,0.0,11.000000,8.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.250000,82.0,2329.0,214.0,1.330000,0.0,57.1,69.5,44.6
1995-05-01T00:00:00,6.0,6.0,7.000000,2.000000,1.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,1.100000,91.0,2472.0,142.0,1.890000,0.0,60.0,72.1,47.9
1995-06-01T00:00:00,83.0,77.0,3.000000,2.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.880000,103.0,2515.0,43.0,1.040000,0.0,66.5,81.1,51.9
1995-07-01T00:00:00,NaN,NaN,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,NaN,...,0.0,0.000000,NaN,NaN,NaN,0.000000,0.0,NaN,NaN,55.1
1995-08-01T00:00:00,NaN,173.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,102.0,NaN,4.0,0.000000,0.0,71.1,90.4,51.9
1995-09-01T00:00:00,NaN,NaN,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,NaN,...,0.0,0.000000,NaN,NaN,NaN,0.000000,0.0,NaN,NaN,51.3
1995-10-01T00:00:00,NaN,NaN,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,NaN,...,0.0,0.000000,NaN,NaN,NaN,0.000000,0.0,NaN,NaN,46.3
1995-11-01T00:00:00,NaN,0.0,2.000000,1.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.170000,81.0,NaN,204.0,0.250000,0.0,57.8,72.5,43.2
1995-12-01T00:00:00,NaN,0.0,14.000000,9.000000,2.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,3.450000,68.0,NaN,391.0,9.950000,0.0,52.0,60.2,43.7
1996-01-01T00:00:00,0.0,0.0,14.000000,10.000000,3.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,3.100000,70.0,NaN,476.0,8.960000,0.0,49.1,57.8,40.5
1996-02-01T00:00:00,0.0,0.0,16.000000,13.000000,1.000000,0.0,0.0,0.0,2.0,0.0,...,0.0,2.000000,75.0,NaN,293.0,8.260000,0.0,53.6,63.5,43.7
1996-03-01T00:00:00,0.0,0.0,7.000000,4.000000,1.000000,0.0,0.0,0.0,1.0,0.0,...,0.0,1.350000,83.0,NaN,263.0,2.610000,0.0,55.3,69.4,41.1
1996-04-01T00:00:00,19.0,19.0,7.000000,5.000000,1.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,2.370000,94.0,NaN,190.0,3.490000,0.0,58.6,72.7,44.4
1996-05-01T00:00:00,60.0,41.0,6.000000,4.000000,2.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,1.510000,94.0,NaN,118.0,3.370000,0.0,62.4,76.9,47.9
1996-06-01T00:00:00,167.0,107.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,103.0,NaN,17.0,0.000000,0.0,68.7,86.9,50.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015-10-01T00:00:00,724.0,64.0,0.000000,0.000000,0.000000,NaN,0.0,0.0,0.0,0.0,...,0.0,0.000000,94.0,48.0,23.0,0.000000,0.0,66.3,82.8,49.9
2015-11-01T00:00:00,724.0,0.0,7.000000,3.000000,0.000000,NaN,NaN,0.0,3.0,0.0,...,NaN,0.670000,75.0,438.0,391.0,1.280000,NaN,51.5,64.4,38.7
2015-12-01T00:00:00,724.0,0.0,15.500000,10.000000,1.500000,NaN,NaN,0.0,8.0,0.0,...,NaN,1.635000,63.0,960.0,522.0,5.210000,NaN,47.6,56.4,38.8
2016-01-01T00:00:00,0.0,0.0,20.333333,16.000000,3.000000,NaN,NaN,0.0,1.0,0.0,...,NaN,1.433333,64.0,1388.0,428.0,9.333333,NaN,50.7,56.7,44.8
2016-02-01T00:00:00,2.0,2.0,6.000000,2.500000,0.000000,NaN,NaN,0.0,0.0,0.0,...,NaN,0.665000,78.0,1701.0,313.0,1.045000,NaN,54.2,67.4,41.1
2016-03-01T00:00:00,2.0,0.0,13.000000,11.000000,2.500000,NaN,NaN,0.0,0.0,0.0,...,NaN,1.795000,75.0,2014.0,313.0,7.495000,NaN,54.6,64.9,44.4
2016-04-01T00:00:00,8.0,7.0,5.333333,3.333333,0.000000,NaN,NaN,0.0,0.0,0.0,...,NaN,0.560000,87.0,2186.0,172.0,1.233333,NaN,59.5,71.9,47.1
2016-05-01T00:00:00,43.0,35.0,2.000000,0.500000,0.000000,NaN,NaN,0.0,0.0,0.0,...,NaN,0.100000,94.0,2300.0,114.0,0.125000,NaN,62.5,75.5,49.5
2016-06-01T00:00:00,159.0,115.0,0.000000,0.000000,0.000000,NaN,NaN,0.0,0.0,0.0,...,NaN,0.000000,97.0,2317.0,17.0,0.000000,NaN,68.4,84.9,51.9
2016-07-01T00:00:00,299.0,140.0,0.000000,0.000000,0.000000,NaN,0.0,0.0,0.0,0.0,...,0.0,0.000000,100.0,11.0,11.0,0.000000,0.0,69.2,86.5,51.8
2016-08-01T00:00:00,399.0,101.0,0.000000,0.000000,0.000000,NaN,NaN,0.0,0.0,0.0,...,NaN,0.000000,97.0,15.0,4.0,0.000000,NaN,68.1,83.7,52.6
2016-09-01T00:00:00,502.0,102.0,0.000000,0.000000,0.000000,NaN,NaN,0.0,0.0,0.0,...,NaN,0.000000,97.0,37.0,23.0,0.000000,NaN,67.7,84.5,50.8
2016-10-01T00:00:00,507.0,5.0,13.000000,9.666667,2.000000,NaN,NaN,0.0,0.0,0.0,...,NaN,1.523333,88.0,167.0,130.0,5.753333,NaN,61.0,72.5,49.5
2016-11-01T00:00:00,507.0,0.0,9.000000,5.000000,0.000000,NaN,NaN,0.0,0.0,0.0,...,NaN,0.600000,75.0,471.0,303.0,1.930000,NaN,54.5,65.2,43.8
2016-12-01T00:00:00,507.0,0.0,8.333333,7.666667,1.666667,NaN,NaN,0.0,11.0,0.0,...,NaN,3.076667,64.0,1014.0,543.0,6.770000,NaN,46.4,57.3,35.4
2017-01-01T00:00:00,0.0,0.0,16.000000,13.500000,5.250000,NaN,NaN,0.0,11.0,0.0,...,NaN,2.250000,62.0,1564.0,549.0,12.182500,NaN,46.7,55.7,37.7
2017-02-01T00:00:00,0.0,0.0,16.500000,15.000000,3.000000,NaN,NaN,0.0,3.0,0.0,...,NaN,2.225000,67.0,1937.0,373.0,10.935000,NaN,51.7,59.5,43.8
2017-03-01T00:00:00,0.0,0.0,8.500000,7.000000,1.000000,NaN,NaN,0.0,1.0,0.0,...,NaN,1.115000,79.0,2208.0,271.0,3.605000,NaN,56.0,68.8,43.1
2017-04-01T00:00:00,0.0,0.0,11.333333,5.666667,0.333333,NaN,NaN,0.0,0.0,0.0,...,NaN,0.813333,82.0,2440.0,232.0,2.130000,NaN,56.7,68.5,45.0
2017-05-01T00:00:00,53.0,53.0,0.000000,0.000000,0.000000,NaN,0.0,0.0,0.0,0.0,...,0.0,0.000000,91.0,2538.0,98.0,0.000000,0.0,63.6,78.4,48.8
2017-06-01T00:00:00,201.0,148.0,2.666667,2.000000,0.000000,NaN,0.0,0.0,0.0,0.0,...,0.0,0.380000,103.0,2564.0,26.0,0.600000,0.0,69.1,84.3,53.8
2017-07-01T00:00:00,371.0,169.0,0.000000,0.000000,0.000000,NaN,NaN,0.0,0.0,0.0,...,NaN,0.000000,104.0,4.0,4.0,0.000000,NaN,70.4,86.8,54.1
2017-08-01T00:00:00,571.0,201.0,0.000000,0.000000,0.000000,NaN,0.0,0.0,0.0,0.0,...,0.0,0.000000,101.0,4.0,0.0,0.000000,0.0,71.5,86.7,56.3
2017-09-01T00:00:00,NaN,NaN,2.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,...,NaN,0.010000,NaN,NaN,NaN,0.020000,NaN,NaN,NaN,NaN
2017-10-01T00:00:00,NaN,NaN,1.000000,1.000000,0.000000,NaN,NaN,NaN,NaN,NaN,...,NaN,0.315000,NaN,NaN,NaN,0.315000,NaN,NaN,NaN,NaN
2017-11-01T00:00:00,NaN,NaN,10.000000,8.500000,1.000000,NaN,NaN,NaN,NaN,NaN,...,NaN,1.300000,NaN,NaN,NaN,3.470000,NaN,NaN,NaN,NaN
2017-12-01T00:00:00,NaN,NaN,2.000000,0.000000,0.000000,NaN,0.0,NaN,NaN,NaN,...,0.0,0.040000,NaN,NaN,NaN,0.050000,0.0,NaN,NaN,NaN
2018-01-01T00:00:00,NaN,NaN,12.000000,8.500000,2.500000,NaN,NaN,NaN,NaN,NaN,...,NaN,1.915000,NaN,NaN,NaN,5.525000,NaN,NaN,NaN,NaN
2018-02-01T00:00:00,NaN,NaN,3.000000,1.000000,0.000000,NaN,0.0,NaN,NaN,NaN,...,0.0,0.175000,NaN,NaN,NaN,0.240000,0.0,NaN,NaN,NaN
2018-03-01T00:00:00,NaN,NaN,17.000000,11.000000,2.000000,NaN,NaN,NaN,NaN,NaN,...,NaN,1.270000,NaN,NaN,NaN,6.000000,NaN,NaN,NaN,NaN

In [20]:
pd.to_datetime(sono2.index)
pd.to_datetime(sono2.index
pd.to_datetime(sono2.index)

DatetimeIndex(['1994-01-01', '1994-02-01', '1994-03-01', '1994-04-01',
               '1994-05-01', '1994-06-01', '1994-07-01', '1994-08-01',
               '1994-09-01', '1994-10-01',
               ...
               '2017-06-01', '2017-07-01', '2017-08-01', '2017-09-01',
               '2017-10-01', '2017-11-01', '2017-12-01', '2018-01-01',
               '2018-02-01', '2018-03-01'],
              dtype='datetime64[ns]', name='date', length=291, freq=None)

In [21]:
sono2["dt"] = pd.to_datetime(sono2.index)
sono2["Year"]=sono2["dt"].dt.year
sono2["Month"] = sono2["dt"].dt.month

In [22]:
sono2

,CDSD,CLDD,DP01,DP10,DP1X,DSND,DSNW,DT00,DT32,DX32,...,HDSD,HTDD,PRCP,SNOW,TAVG,TMAX,TMIN,dt,Year,Month
date,,,,,,,,,,,,,,,,,,,,,
1994-01-01T00:00:00,0.0,0.0,10.000000,4.000000,1.000000,0.0,0.0,0.0,8.0,0.0,...,NaN,449.0,3.360000,0.0,47.6,59.5,35.8,1994-01-01,1994,1
1994-02-01T00:00:00,0.0,0.0,11.000000,9.000000,1.000000,0.0,0.0,0.0,7.0,0.0,...,NaN,385.0,5.460000,0.0,49.1,60.9,37.3,1994-02-01,1994,2
1994-03-01T00:00:00,2.0,2.0,2.000000,1.000000,0.000000,0.0,0.0,0.0,1.0,0.0,...,NaN,244.0,0.230000,0.0,56.2,71.0,41.3,1994-03-01,1994,3
1994-04-01T00:00:00,NaN,NaN,6.000000,4.000000,0.000000,0.0,0.0,0.0,0.0,NaN,...,NaN,NaN,1.330000,0.0,NaN,NaN,42.7,1994-04-01,1994,4
1994-05-01T00:00:00,NaN,14.0,5.000000,3.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,NaN,96.0,1.370000,0.0,62.0,76.6,47.4,1994-05-01,1994,5
1994-06-01T00:00:00,NaN,92.0,1.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,NaN,11.0,0.050000,0.0,68.0,87.5,48.5,1994-06-01,1994,6
1994-07-01T00:00:00,NaN,90.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,4.0,4.0,0.000000,0.0,67.9,84.6,51.1,1994-07-01,1994,7
1994-08-01T00:00:00,NaN,134.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,5.0,0.0,0.000000,0.0,70.2,90.1,50.2,1994-08-01,1994,8
1994-09-01T00:00:00,NaN,85.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,12.0,7.0,0.000000,0.0,67.9,86.0,49.9,1994-09-01,1994,9
1994-10-01T00:00:00,NaN,12.0,2.000000,2.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,114.0,102.0,0.590000,0.0,61.8,78.9,44.8,1994-10-01,1994,10
1994-11-01T00:00:00,NaN,0.0,9.000000,5.000000,2.000000,0.0,0.0,0.0,7.0,0.0,...,564.0,450.0,6.490000,0.0,48.4,59.6,37.2,1994-11-01,1994,11
1994-12-01T00:00:00,NaN,0.0,12.000000,9.000000,0.000000,0.0,0.0,0.0,7.0,0.0,...,1071.0,508.0,3.910000,0.0,45.6,54.8,36.3,1994-12-01,1994,12
1995-01-01T00:00:00,0.0,0.0,20.000000,18.000000,7.000000,0.0,0.0,0.0,2.0,0.0,...,1475.0,403.0,20.290000,0.0,51.2,57.5,44.8,1995-01-01,1995,1
1995-02-01T00:00:00,0.0,0.0,2.000000,2.000000,0.000000,0.0,0.0,0.0,2.0,0.0,...,1762.0,287.0,0.820000,0.0,54.0,63.6,44.4,1995-02-01,1995,2
1995-03-01T00:00:00,0.0,0.0,16.000000,14.000000,4.000000,0.0,0.0,0.0,0.0,0.0,...,2115.0,353.0,13.300000,0.0,52.8,63.0,42.5,1995-03-01,1995,3
1995-04-01T00:00:00,0.0,0.0,11.000000,8.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,2329.0,214.0,1.330000,0.0,57.1,69.5,44.6,1995-04-01,1995,4
1995-05-01T00:00:00,6.0,6.0,7.000000,2.000000,1.000000,0.0,0.0,0.0,0.0,0.0,...,2472.0,142.0,1.890000,0.0,60.0,72.1,47.9,1995-05-01,1995,5
1995-06-01T00:00:00,83.0,77.0,3.000000,2.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,2515.0,43.0,1.040000,0.0,66.5,81.1,51.9,1995-06-01,1995,6
1995-07-01T00:00:00,NaN,NaN,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,NaN,...,NaN,NaN,0.000000,0.0,NaN,NaN,55.1,1995-07-01,1995,7
1995-08-01T00:00:00,NaN,173.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,NaN,4.0,0.000000,0.0,71.1,90.4,51.9,1995-08-01,1995,8
1995-09-01T00:00:00,NaN,NaN,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,NaN,...,NaN,NaN,0.000000,0.0,NaN,NaN,51.3,1995-09-01,1995,9
1995-10-01T00:00:00,NaN,NaN,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,NaN,...,NaN,NaN,0.000000,0.0,NaN,NaN,46.3,1995-10-01,1995,10
1995-11-01T00:00:00,NaN,0.0,2.000000,1.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,NaN,204.0,0.250000,0.0,57.8,72.5,43.2,1995-11-01,1995,11
1995-12-01T00:00:00,NaN,0.0,14.000000,9.000000,2.000000,0.0,0.0,0.0,0.0,0.0,...,NaN,391.0,9.950000,0.0,52.0,60.2,43.7,1995-12-01,1995,12
1996-01-01T00:00:00,0.0,0.0,14.000000,10.000000,3.000000,0.0,0.0,0.0,0.0,0.0,...,NaN,476.0,8.960000,0.0,49.1,57.8,40.5,1996-01-01,1996,1
1996-02-01T00:00:00,0.0,0.0,16.000000,13.000000,1.000000,0.0,0.0,0.0,2.0,0.0,...,NaN,293.0,8.260000,0.0,53.6,63.5,43.7,1996-02-01,1996,2
1996-03-01T00:00:00,0.0,0.0,7.000000,4.000000,1.000000,0.0,0.0,0.0,1.0,0.0,...,NaN,263.0,2.610000,0.0,55.3,69.4,41.1,1996-03-01,1996,3
1996-04-01T00:00:00,19.0,19.0,7.000000,5.000000,1.000000,0.0,0.0,0.0,0.0,0.0,...,NaN,190.0,3.490000,0.0,58.6,72.7,44.4,1996-04-01,1996,4
1996-05-01T00:00:00,60.0,41.0,6.000000,4.000000,2.000000,0.0,0.0,0.0,0.0,0.0,...,NaN,118.0,3.370000,0.0,62.4,76.9,47.9,1996-05-01,1996,5
1996-06-01T00:00:00,167.0,107.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,NaN,17.0,0.000000,0.0,68.7,86.9,50.5,1996-06-01,1996,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015-10-01T00:00:00,724.0,64.0,0.000000,0.000000,0.000000,NaN,0.0,0.0,0.0,0.0,...,48.0,23.0,0.000000,0.0,66.3,82.8,49.9,2015-10-01,2015,10
2015-11-01T00:00:00,724.0,0.0,7.000000,3.000000,0.000000,NaN,NaN,0.0,3.0,0.0,...,438.0,391.0,1.280000,NaN,51.5,64.4,38.7,2015-11-01,2015,11
2015-12-01T00:00:00,724.0,0.0,15.500000,10.000000,1.500000,NaN,NaN,0.0,8.0,0.0,...,960.0,522.0,5.210000,NaN,47.6,56.4,38.8,2015-12-01,2015,12
2016-01-01T00:00:00,0.0,0.0,20.333333,16.000000,3.000000,NaN,NaN,0.0,1.0,0.0,...,1388.0,428.0,9.333333,NaN,50.7,56.7,44.8,2016-01-01,2016,1
2016-02-01T00:00:00,2.0,2.0,6.000000,2.500000,0.000000,NaN,NaN,0.0,0.0,0.0,...,1701.0,313.0,1.045000,NaN,54.2,67.4,41.1,2016-02-01,2016,2
2016-03-01T00:00:00,2.0,0.0,13.000000,11.000000,2.500000,NaN,NaN,0.0,0.0,0.0,...,2014.0,313.0,7.495000,NaN,54.6,64.9,44.4,2016-03-01,2016,3
2016-04-01T00:00:00,8.0,7.0,5.333333,3.333333,0.000000,NaN,NaN,0.0,0.0,0.0,...,2186.0,172.0,1.233333,NaN,59.5,71.9,47.1,2016-04-01,2016,4
2016-05-01T00:00:00,43.0,35.0,2.000000,0.500000,0.000000,NaN,NaN,0.0,0.0,0.0,...,2300.0,114.0,0.125000,NaN,62.5,75.5,49.5,2016-05-01,2016,5
2016-06-01T00:00:00,159.0,115.0,0.000000,0.000000,0.000000,NaN,NaN,0.0,0.0,0.0,...,2317.0,17.0,0.000000,NaN,68.4,84.9,51.9,2016-06-01,2016,6
2016-07-01T00:00:00,299.0,140.0,0.000000,0.000000,0.000000,NaN,0.0,0.0,0.0,0.0,...,11.0,11.0,0.000000,0.0,69.2,86.5,51.8,2016-07-01,2016,7
2016-08-01T00:00:00,399.0,101.0,0.000000,0.000000,0.000000,NaN,NaN,0.0,0.0,0.0,...,15.0,4.0,0.000000,NaN,68.1,83.7,52.6,2016-08-01,2016,8
2016-09-01T00:00:00,502.0,102.0,0.000000,0.000000,0.000000,NaN,NaN,0.0,0.0,0.0,...,37.0,23.0,0.000000,NaN,67.7,84.5,50.8,2016-09-01,2016,9
2016-10-01T00:00:00,507.0,5.0,13.000000,9.666667,2.000000,NaN,NaN,0.0,0.0,0.0,...,167.0,130.0,5.753333,NaN,61.0,72.5,49.5,2016-10-01,2016,10
2016-11-01T00:00:00,507.0,0.0,9.000000,5.000000,0.000000,NaN,NaN,0.0,0.0,0.0,...,471.0,303.0,1.930000,NaN,54.5,65.2,43.8,2016-11-01,2016,11
2016-12-01T00:00:00,507.0,0.0,8.333333,7.666667,1.666667,NaN,NaN,0.0,11.0,0.0,...,1014.0,543.0,6.770000,NaN,46.4,57.3,35.4,2016-12-01,2016,12
2017-01-01T00:00:00,0.0,0.0,16.000000,13.500000,5.250000,NaN,NaN,0.0,11.0,0.0,...,1564.0,549.0,12.182500,NaN,46.7,55.7,37.7,2017-01-01,2017,1
2017-02-01T00:00:00,0.0,0.0,16.500000,15.000000,3.000000,NaN,NaN,0.0,3.0,0.0,...,1937.0,373.0,10.935000,NaN,51.7,59.5,43.8,2017-02-01,2017,2
2017-03-01T00:00:00,0.0,0.0,8.500000,7.000000,1.000000,NaN,NaN,0.0,1.0,0.0,...,2208.0,271.0,3.605000,NaN,56.0,68.8,43.1,2017-03-01,2017,3
2017-04-01T00:00:00,0.0,0.0,11.333333,5.666667,0.333333,NaN,NaN,0.0,0.0,0.0,...,2440.0,232.0,2.130000,NaN,56.7,68.5,45.0,2017-04-01,2017,4
2017-05-01T00:00:00,53.0,53.0,0.000000,0.000000,0.000000,NaN,0.0,0.0,0.0,0.0,...,2538.0,98.0,0.000000,0.0,63.6,78.4,48.8,2017-05-01,2017,5
2017-06-01T00:00:00,201.0,148.0,2.666667,2.000000,0.000000,NaN,0.0,0.0,0.0,0.0,...,2564.0,26.0,0.600000,0.0,69.1,84.3,53.8,2017-06-01,2017,6
2017-07-01T00:00:00,371.0,169.0,0.000000,0.000000,0.000000,NaN,NaN,0.0,0.0,0.0,...,4.0,4.0,0.000000,NaN,70.4,86.8,54.1,2017-07-01,2017,7
2017-08-01T00:00:00,571.0,201.0,0.000000,0.000000,0.000000,NaN,0.0,0.0,0.0,0.0,...,4.0,0.0,0.000000,0.0,71.5,86.7,56.3,2017-08-01,2017,8
2017-09-01T00:00:00,NaN,NaN,2.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.020000,NaN,NaN,NaN,NaN,2017-09-01,2017,9
2017-10-01T00:00:00,NaN,NaN,1.000000,1.000000,0.000000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.315000,NaN,NaN,NaN,NaN,2017-10-01,2017,10
2017-11-01T00:00:00,NaN,NaN,10.000000,8.500000,1.000000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,3.470000,NaN,NaN,NaN,NaN,2017-11-01,2017,11
2017-12-01T00:00:00,NaN,NaN,2.000000,0.000000,0.000000,NaN,0.0,NaN,NaN,NaN,...,NaN,NaN,0.050000,0.0,NaN,NaN,NaN,2017-12-01,2017,12
2018-01-01T00:00:00,NaN,NaN,12.000000,8.500000,2.500000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,5.525000,NaN,NaN,NaN,NaN,2018-01-01,2018,1
2018-02-01T00:00:00,NaN,NaN,3.000000,1.000000,0.000000,NaN,0.0,NaN,NaN,NaN,...,NaN,NaN,0.240000,0.0,NaN,NaN,NaN,2018-02-01,2018,2
2018-03-01T00:00:00,NaN,NaN,17.000000,11.000000,2.000000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,6.000000,NaN,NaN,NaN,NaN,2018-03-01,2018,3

In [44]:
sonoyear = sono2.groupby("Year")

In [70]:
yeardic = {}
for group, item in sonoyear:
    monthdic = {}
    for index, row in item.iterrows():
        monthdic.update({"PRCP {}".format(row["Month"]): row["PRCP"] , 
                "TAVG {}" .format(row["Month"]) : row["TAVG"],
                "TMIN {}" . format(row["Month"]) : row["TMIN"],
                "TMAX {}" . format(row["Month"]) : row["TMAX"]})
    x= {group : monthdic}
    yeardic.update(x)

In [75]:
yeardf = pd.DataFrame.from_dict(yeardic, orient='index')

In [82]:
yeardf

,PRCP 1,TAVG 1,TMIN 1,TMAX 1,PRCP 2,TAVG 2,TMIN 2,TMAX 2,PRCP 3,TAVG 3,...,TMIN 10,TMAX 10,PRCP 11,TAVG 11,TMIN 11,TMAX 11,PRCP 12,TAVG 12,TMIN 12,TMAX 12
1994,3.360000,47.6,35.8,59.5,5.460,49.1,37.3,60.9,0.230,56.2,...,44.8,78.9,6.490,48.4,37.2,59.6,3.910,45.6,36.3,54.8
1995,20.290000,51.2,44.8,57.5,0.820,54.0,44.4,63.6,13.300,52.8,...,46.3,NaN,0.250,57.8,43.2,72.5,9.950,52.0,43.7,60.2
1996,8.960000,49.1,40.5,57.8,8.260,53.6,43.7,63.5,2.610,55.3,...,47.2,77.9,3.480,55.0,43.9,66.2,13.110,50.4,42.0,58.8
1997,10.350000,48.8,41.1,56.6,0.650,52.7,39.3,66.0,1.020,56.2,...,47.8,NaN,7.480,NaN,45.3,NaN,3.550,47.7,37.6,57.8
1998,12.000000,50.1,42.9,57.2,18.900,50.2,42.4,58.0,2.310,NaN,...,46.0,76.7,5.670,52.7,42.7,62.6,1.440,44.7,33.3,56.0
1999,4.210000,46.4,37.0,55.8,11.330,49.1,38.8,59.3,4.130,50.2,...,45.8,NaN,3.190,55.2,44.9,65.5,0.880,48.7,35.9,61.6
2000,5.710000,50.0,41.1,59.0,10.810,52.0,43.7,60.2,2.740,54.5,...,48.4,74.3,1.220,NaN,38.4,NaN,1.590,47.7,36.4,58.9
2001,3.370000,45.8,33.1,58.4,4.740,49.3,38.8,59.8,1.730,56.0,...,49.0,NaN,8.580,54.8,44.1,65.6,11.000,49.3,42.7,55.9
2002,3.980000,46.7,36.4,57.1,2.530,52.0,39.1,64.9,2.670,52.6,...,46.0,77.8,3.950,56.1,43.2,69.0,9.970,49.1,40.5,57.7
2003,3.000000,NaN,43.9,NaN,2.290,50.8,38.6,63.1,2.380,54.9,...,46.8,NaN,2.880,50.5,39.8,61.3,7.950,NaN,41.1,NaN
2004,3.000000,NaN,40.2,NaN,6.310,50.6,40.9,60.3,1.060,60.1,...,48.4,72.8,2.310,53.0,42.4,63.6,10.430,NaN,39.1,NaN
2005,4.190000,46.3,38.2,54.3,4.360,52.6,43.0,62.2,4.780,NaN,...,46.5,NaN,1.840,55.5,42.9,68.1,14.440,50.0,41.1,58.9
2006,3.880000,49.1,39.7,58.5,4.110,50.6,37.6,63.6,8.000,48.6,...,45.3,NaN,4.200,53.4,42.5,64.3,4.610,47.4,36.8,57.9
2007,0.470000,45.1,31.6,58.6,5.930,49.6,39.1,60.1,0.030,57.0,...,46.9,NaN,0.650,NaN,42.3,NaN,4.240,47.3,37.6,57.0
2008,11.010000,45.6,37.2,54.0,3.810,50.2,38.5,62.0,0.210,53.5,...,45.9,NaN,2.660,55.7,43.6,67.8,1.570,45.1,35.0,55.2
2009,0.240000,48.9,35.2,62.6,8.760,NaN,39.0,NaN,2.300,52.7,...,47.9,NaN,0.450,52.4,39.4,65.5,2.400,45.8,37.0,54.6
2010,8.300000,48.2,41.6,54.9,4.080,51.2,41.1,61.2,2.395,NaN,...,48.8,NaN,2.920,53.3,41.9,64.7,9.405,NaN,42.9,NaN
2011,1.990000,NaN,37.0,NaN,4.520,48.0,35.9,60.2,NaN,51.2,...,48.1,76.5,NaN,50.1,38.1,62.0,0.240,NaN,34.5,NaN
2012,5.670000,NaN,35.7,NaN,1.550,51.6,38.7,64.4,8.090,NaN,...,49.1,75.3,5.855,54.4,44.1,64.7,7.730,47.0,38.1,56.0
2013,0.870000,45.4,33.5,57.3,0.455,NaN,NaN,NaN,0.820,54.0,...,42.6,76.8,0.930,NaN,NaN,NaN,0.510,45.3,31.5,59.1
2014,0.085000,51.7,36.1,67.2,10.545,51.9,41.4,62.4,3.600,NaN,...,49.1,80.3,3.030,55.9,43.6,68.2,14.915,52.6,46.2,58.9
2015,0.030000,50.7,38.7,62.6,2.275,54.7,42.3,67.0,0.265,57.7,...,49.9,82.8,1.280,51.5,38.7,64.4,5.210,47.6,38.8,56.4
2016,9.333333,50.7,44.8,56.7,1.045,54.2,41.1,67.4,7.495,54.6,...,49.5,72.5,1.930,54.5,43.8,65.2,6.770,46.4,35.4,57.3
2017,12.182500,46.7,37.7,55.7,10.935,51.7,43.8,59.5,3.605,56.0,...,NaN,NaN,3.470,NaN,NaN,NaN,0.050,NaN,NaN,NaN
2018,5.525000,NaN,NaN,NaN,0.240,NaN,NaN,NaN,6.000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN